### ISSUE TITLE
麻烦修复下错误

### ISSUE THREAD

**Issue by chenghl666** [Joe1sn/ExtCheats#1]
麻烦修复下错误
![image](https://github.com/Joe1sn/ExtCheats/assets/123218493/aaf909d9-034c-40bd-8205-eba5701d8514)

**Comment by Joe1sn** [comment]
![image](https://github.com/Joe1sn/ExtCheats/assets/37005640/b7f693c6-6943-4115-b310-ecb320978c2f)
![image](https://github.com/Joe1sn/ExtCheats/assets/37005640/daa23d9d-db9b-4f6b-a5be-b628212e1e9c)
我在桌面git clone仓库，然后使用visual studio 2022进行编译，没有任何问题。能否给出你的编译环境？

**Comment by Joe1sn** [comment]
项目使用了 d3d11的SDK，自己编译的话确保SDK被安装
